name: Publish package to the Maven Central Repository

on:
  release:
    types: [created]

jobs:
  deploy:
    uses: FontysVenlo/alda_api_workflows/.github/workflows/deploy.yml@main
    secrets: inherit
    with:
      tag: ${{ github.event.release.tag_name }}